# Generated by Django 3.1.7 on 2021-03-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('File', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Through',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ForUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filemodels', to='socialaccount.socialaccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='throughmodel',
            name='foruser',
        ),
        migrations.DeleteModel(
            name='Fileobj',
        ),
        migrations.DeleteModel(
            name='Throughmodel',
        ),
        migrations.AddField(
            model_name='fileobject',
            name='UserThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='HOME.through'),
        ),
    ]
