# Generated by Django 3.1.7 on 2021-03-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_fileobject_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileobject',
            name='loc',
        ),
    ]
