# Generated by Django 3.1.7 on 2021-03-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throughmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foruser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filemodel', to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Fileobj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='documents')),
                ('userthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='HOME.throughmodel')),
            ],
        ),
    ]
